apiVersion: v1
name: ack-dynamodb-controller
description: A Helm chart for the ACK service controller for dynamodb
version: v0.0.3
appVersion: v0.0.3
home: https://github.com/aws-controllers-k8s/dynamodb-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/dynamodb-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: dynamodb Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/dynamodb-maintainer
keywords:
  - aws
  - kubernetes
  - dynamodb
